/**
 * One-off importer that turns a raw, openly-licensed skills taxonomy into the
 * committed seed at src/domain/data/skill-seed.json. NOT part of `npm test`.
 *
 *   npm run build:skill-seed -- path/to/taxonomy.csv [labelColumn] [categoryColumn]
 *
 * The raw taxonomy (e.g. O*NET "Technology Skills.txt", tab-delimited, or an ESCO
 * skills CSV) is downloaded once, manually, and is NOT committed — only the
 * normalized, generated artifact is. Each label is run through `normalizeSkill`,
 * de-duplicated (first category wins), sorted, and tagged with a coarse category.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { normalizeSkill } from "../src/domain/normalize";

const SOURCE =
  "O*NET 28.3 Technology Skills + Skills/Knowledge elements (U.S. DOL) and the ESCO skills pillar (European Commission)";
const LICENCE = "O*NET: public domain (U.S. Department of Labor); ESCO: CC BY 4.0";

function parseRow(line: string, delimiter: string): string[] {
  if (delimiter === "\t") {
    return line.split("\t");
  }
  // Minimal CSV: handles double-quoted fields containing commas.
  const fields: string[] = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === "," && !inQuotes) {
      fields.push(current);
      current = "";
    } else {
      current += char;
    }
  }
  fields.push(current);
  return fields;
}

function main(): void {
  const [, , csvPath, labelColumn = "label", categoryColumn = "category"] = process.argv;
  if (!csvPath) {
    console.error("usage: build-skill-seed <taxonomy.csv> [labelColumn] [categoryColumn]");
    process.exitCode = 1;
    return;
  }

  const raw = readFileSync(csvPath, "utf8").trim();
  const lines = raw.split(/\r?\n/);
  const headerLine = lines[0] ?? "";
  const delimiter = headerLine.includes("\t") ? "\t" : ",";
  const header = parseRow(headerLine, delimiter).map((h) => h.trim().toLowerCase());
  const labelIdx = header.indexOf(labelColumn.toLowerCase());
  const categoryIdx = header.indexOf(categoryColumn.toLowerCase());
  if (labelIdx === -1) {
    console.error(`label column "${labelColumn}" not found in header: ${header.join(", ")}`);
    process.exitCode = 1;
    return;
  }

  const byName = new Map<string, string>();
  for (const line of lines.slice(1)) {
    if (!line.trim()) {
      continue;
    }
    const cells = parseRow(line, delimiter);
    const label = cells[labelIdx];
    if (!label?.trim()) {
      continue;
    }
    const name = normalizeSkill(label);
    if (!byName.has(name)) {
      byName.set(name, cells[categoryIdx]?.trim() || "general");
    }
  }

  const skills = [...byName.entries()]
    .map(([name, category]) => ({ name, category }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const outPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "../src/domain/data/skill-seed.json",
  );
  const payload = {
    source: SOURCE,
    licence: LICENCE,
    retrievedAt: new Date().toISOString().slice(0, 10),
    note: "Generated by scripts/build-skill-seed.ts from the raw taxonomy CSV. Do not edit by hand; re-run the importer.",
    skills,
  };
  writeFileSync(outPath, `${JSON.stringify(payload, null, 2)}\n`);
  console.log(`wrote ${skills.length} skills to ${outPath}`);
}

main();
